// <auto-generated />
namespace Xero.Refactor.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetNavigationProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetNavigationProp));
        
        string IMigrationMetadata.Id
        {
            get { return "201708260451022_SetNavigationProp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
